### PR TITLE
add charts

### PR DESCRIPTION
**Pull request by Tarzeron**

### CODE REVIEW

**Comment by VadimGrozinok** [comment]
There are some remarks about comments.
    7.Add tooltips for points in charts
Tooltips are already on charts, it just shows with some delay.
    10.The first date on the chart with "per hour" filter is 09.08.2019, while with the "per day" filter it's 10.08.2019
It's right because data per hour appears in DB earlier than data per day.

**Comment by shotgunofdeath** [comment]
As for those tooltips... As a suggestion, you can at least enlarge the hover radius of initializing for the points. Now it's pretty hard to make them appear...

**Comment by VadimGrozinok** [comment]
Ok, I understand. We will do it.

**Comment by shotgunofdeath** [comment]
Hi there!
1. There are still some problems with Header.vue on the index page:
- @media(max-width: 1366px) => the dropdown with coins has different font-size from other navigation items.
- When the window is 991px wide naviagtion links in the header disappear and the burger menu with those links inside becomes visible. The problem is that there is no link to the new page in the menu  whatsoever.

2. The footer for internal pages has a bit different look. there's a special flag(isInternal) for this logic in Footer.vue.

3. Improvements for tooltips in charts. The hover radius for the points was meant to be changed, not the points themselves. But, it's a good idea to change their size only on hover, so that the user can notice them when he choses them.

4. "No data" text shouldn't be hardcoded.

**Pull request merged**
